version: "3"
services:
  postgresql:
    image: postgres:12.5
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: pg_isready -U postgres
      start_period: 10s
      interval: 10s
      timeout: 30s
      retries: 3
  app: &app
    build:
      context: .
    depends_on:
      - postgresql
    volumes:
      - .:/app
    environment:
      - PG_HOST=postgresql
